- .goreleaser.yaml
> fix: Fix docker registry

- api/types/environment.go
Signed-off-by: Wei Zhang <kweizh@gmail.com>
> :bug: fix json tag to snake_case

- .github/workflows/CI.yml
- .golangci.yml
- api/types/environment.go
- client/environment_list.go
- pkg/server/environment_create.go
- pkg/server/environment_list.go
- pkg/server/server.go
It is to support envd create command. The new get endpoint will be used in envdengine.IsRunning.
> feat(env): Support env creation

- manifests/deployment.yaml
> fix: Enable forwarding in ssh config

- api/types/auth.go
- api/types/environment.go
- pkg/docs/docs.go
- pkg/server/auth_middleware.go
- pkg/server/auth_midlleware.go
- pkg/server/environment_list.go
- pkg/server/environment_remove.go
- pkg/server/server.go
> chore: Use middleware to auth

- manifests/templates/deployment.yaml
- manifests/templates/service.yaml
- manifests/values.yaml
> chore: Add nodeport support

- api/types/environment.go
- client/environment_get.go
- pkg/docs/docs.go
- pkg/server/environment_create.go
- pkg/server/environment_list.go
> chore: Update environment types and add get in client

- README.md
- manifests/values.yaml
> chore: update readme toturial

- Makefile
- cmd/envd-server/main.go
- pkg/server/auth.go
- pkg/server/containerssh.go
- pkg/server/environment_create.go
- pkg/server/environment_get.go
- pkg/server/environment_list.go
- pkg/server/environment_remove.go
- pkg/server/ping.go
* related to https://github.com/tensorchord/envd/pull/1096
> feat: rm env will rm pod and service

- pkg/server/auth_middleware.go
- pkg/server/environment_get.go
> chore: avoid rewrite the status code when auth failed

- Dockerfile
Fix https://github.com/tensorchord/envd-server/issues/38
> bug: fix certificate problem on k8s pod

- api/types/environment.go
- pkg/consts/consts.go
- pkg/server/environment_create.go
- pkg/util/imageutil/label.go
> feat: clone git repo when info available

- api/types/image.go
- client/image_get.go
- client/image_list.go
- pkg/docs/docs.go
- pkg/server/environment_create.go
- pkg/server/environment_get.go
- pkg/server/image_get.go
- pkg/server/image_list.go
- pkg/server/server.go
* to support https://github.com/tensorchord/envd/issues/1027#issuecomment-1290226640
> feat: add image get and image list

- client/image_get.go
- pkg/server/environment_create.go
- pkg/server/image_get.go
Signed-off-by: Keming <kemingy94@gmail.com>
> chore: add debug info to env create

- go.mod
- pkg/consts/consts.go
- pkg/server/environment_list.go
- pkg/util/filter.go
I noticed this feature that I'm very interested in, so I read it and solved a to-do. In addition, is there anything I can do for this project?
> feat: filter label when generateEnvironmentFromPod

- pkg/server/environment_create.go
> fix: inpsect image size from layer data

- api/types/environment.go
- pkg/consts/consts.go
- pkg/docs/docs.go
- pkg/server/environment_list.go
* related to https://github.com/tensorchord/envd/issues/1045
> refact: move environment struct to server

- cmd/envd-server/main.go
- manifests/values.yaml
- pkg/docs/docs.go
> chore: update version in the code and helm

- pkg/consts/consts.go
- pkg/server/environment_create.go
- pkg/server/environment_get.go
- pkg/server/environment_list.go
- pkg/server/environment_remove.go
> refact: align image lable prefix and pod label prefix

- .github/chart-publish-config.yaml
- .github/workflows/release.yml
- Makefile
- manifests/templates/configmap.yaml
- manifests/templates/deployment.yaml
Ref https://github.com/tensorchord/envd-docs/pull/187#discussion_r1022996771
> feat: Add metrics and update chart

- .github/workflows/release.yml
- manifests/values.yaml
> chore: Update default version in chart

- .github/workflows/CI.yml
- Makefile
- go.mod
- go.sum
- pkg/server/auth_middleware.go
- pkg/server/environment_create.go
- pkg/server/environment_get.go
- pkg/server/environment_list.go
- pkg/server/environment_remove.go
- pkg/server/server.go
- test/environments/list_test.go
- test/environments/suite_test.go
- test/util/environment.go
- test/util/server.go
Ref #65 
Add an integration test case for the environment list.
> chore: Add test cases for environment list

- pkg/image/image.go
- pkg/server/environment_create.go
> chore: Refactor image fetch

- .github/workflows/CI.yml
> ci: fix golang-lint timeout

- client/options.go
- cmd/envd-server/main.go
- go.mod
- go.sum
- manifests/templates/deployment.yaml
- manifests/values.yaml
- pkg/docs/docs.go
- pkg/server/server.go
> bug: fix client incorrectly assembles the api path

- pkg/server/environment_create.go
> bug: Fix #104

- pkg/server/auth.go
- pkg/server/auth_middleware.go
- pkg/server/containerssh.go
- pkg/server/server.go
- pkg/service/user/user.go
Ref #110 
This PR is to:
- Refactor user service
> fix: Keep user service in server, instead of creating

- .github/workflows/release.yml
> bug: fix migration image release

- manifests/templates/deployment.yaml
- manifests/templates/postgres.yaml
- manifests/values.yaml
- pkg/server/auth.go
- pkg/server/auth_middleware.go
- pkg/server/containerssh.go
- pkg/server/handler.go
- pkg/service/user/user.go
> fix: Fix bugs in manifests

- pkg/server/auth.go
- pkg/server/handler.go
- pkg/service/user/user.go
Fix https://github.com/tensorchord/envd-server/issues/122
/assign @kemingy 
> chore: Disable debug in release mode

- manifests/templates/deployment.yaml
- manifests/values.yaml
- pkg/app/server.go
- pkg/runtime/kubernetes/environment_create.go
- pkg/runtime/kubernetes/kubernetes.go
- pkg/server/server.go
- test/util/server.go
Close #81 
Added a new CLI flag image-pull-secret-name and a helm config server.imagePullSecret.
> feat: Support image pull secret

- .github/workflows/release.yml
> chore: add migration image arm support 

- README.md
> docs: add dev locally guide

- api/types/image.go
- client/image_get.go
- dashboard/src/composables/types/scheme.ts
- pkg/docs/docs.go
- pkg/query/image.sql.go
- pkg/query/mock/mock.go
- pkg/query/models.go
- pkg/query/querier.go
- pkg/server/image_get.go
- pkg/server/image_list.go
- pkg/service/image/image.go
- pkg/service/image/metadata.go
- pkg/service/image/util.go
- sql/README.md
- sql/atlas_schema.hcl
- sql/query/image.sql
- sql/schema/20221221100643_rename_identity_token_and_add_packages.sql
- sql/schema/atlas.sum
This PR is to:
- Add apt packages, python packages, and ports in image_info table.
Close #132 
> feat: Add more detail in image table

- .github/workflows/release.yml
> chore: disable update manifest action

- .github/workflows/jslint.yml
- .github/workflows/release.yml
- manifests/templates/deployment.yaml
> chore: remove prefix v in migration image tag and add build action

- manifests/values.yaml
- pkg/server/containerssh.go
- pkg/server/key_create.go
> fix: Fix run bug

- manifests/templates/deployment.yaml
- manifests/templates/postgres.yaml
- manifests/templates/resourcequota.yaml
- manifests/values.yaml
> feat: Add resource quota in helm chart

- manifests/templates/deployment.yaml
- pkg/app/server.go
- pkg/runtime/kubernetes/environment_create.go
- pkg/runtime/kubernetes/kubernetes.go
- pkg/server/server.go
- test/util/server.go
> feat: Support resource quota in envd server

- api/types/environment.go
- cmd/envd-server/main.go
- pkg/docs/docs.go
- pkg/runtime/kubernetes/const.go
- pkg/runtime/kubernetes/environment_create.go
- pkg/server/environment_create.go
- pkg/server/environment_get.go
- pkg/server/environment_list.go
- pkg/server/environment_remove.go
- pkg/server/image_get.go
- pkg/server/image_list.go
- pkg/server/key_create.go
* related to https://github.com/tensorchord/envd/issues/1429
> feat: support config shm size

- pkg/docs/docs.go
- pkg/server/containerssh.go
- pkg/server/handler.go
* fix https://github.com/tensorchord/envd-server/issues/163
refer to https://containerssh.io/reference/api/authconfig/
> fix: containerssh pubkey auth and config endpoint

- sql/README.md
- sql/atlas_schema.hcl
- sql/schema/20230119145105_alter_image_digest_index.sql
- sql/schema/atlas.sum
> bug: fix db schema constraint 

- README.md
- manifests/values.yaml
> minor fix for readme, upgrade version

- .golangci.yml
- go.mod
- pkg/runtime/kubernetes/environment_create.go
- pkg/runtime/provisioner.go
- pkg/server/auth.go
- pkg/service/image/image.go
- pkg/service/image/metadata.go
- pkg/service/user/user.go
No issues for `unused` and `unconvert`.
Signed-off-by: Zhizhen He <hezhizhen.yi@gmail.com>
> fix: add more linters and address related issues
